export const iocns_default = [
	{icon: 'gift'},
	{icon: 'activity'},
	{icon: 'aperture'},
	{icon: 'anchor'},
	{icon: 'shopping-cart'},
	{icon: 'shopping-bag'},
	{icon: 'credit-card'},
	{icon: 'droplet'},
	{icon: 'feather'},
	{icon: 'film'},
	{icon: 'flag'},
	{icon: 'heart'},
	{icon: 'map'},
	{icon: 'moon'},
	{icon: 'package'},
	{icon: 'music'},
	{icon: 'phone-call'},
	{icon: 'send'},
	{icon: 'tablet'},
	{icon: 'trending-up'},
	{icon: 'truck'},
	{icon: 'tv'},
	{icon: 'dollar-sign'},
	{icon: 'trending-down'},
];
